kubectl -n argocd apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-inspector
spec:
  project: default
  source:
    repoURL: 'https://gitlab.zhejianglab.com/AaronYang/euclid-mcp.git'
    targetRevision: main
    path: mcp-inspector/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
EOF
