apiVersion: apps/v1
kind: Deployment
metadata:
  name: euclid-catalog-mcp
spec:
  template:
    spec:
      containers:
        - name: euclid-catalog-mcp
          image: crpi-wixjy6gci86ms14e.cn-hongkong.personal.cr.aliyuncs.com/ay-dev/euclid-catalog-mcp:v2026026
