kubectl -n argocd apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: euclid-catalog-mcp
spec:
  project: default
  source:
    repoURL: 'https://gitlab.zhejianglab.com/AaronYang/euclid-mcp.git'
    targetRevision: main
    path: analysis-catalog/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
EOF