apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: euclid-crossmatch-mcp
  labels:
    app: euclid-crossmatch-mcp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "self-signed-ca-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - crossmatch.euclid.mcp.ay.dev
      secretName: euclid-crossmatch-tls
  rules:
    - host: crossmatch.euclid.mcp.ay.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: euclid-crossmatch-mcp
                port:
                  number: 8000
