apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  type: NodePort
  ports:
    - port: 6274
      targetPort: 6274
      protocol: TCP
      name: web
      nodePort: 32225
    - port: 6277
      targetPort: 6277
      protocol: TCP
      name: mcp
      nodePort: 32220
  selector:
    app: mcp-inspector
