apiVersion: v1
kind: Secret
metadata:
  name: euclid-catalog-mcp-secret
  labels:
    app: euclid-catalog-mcp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "Q2hkb3NGYVpoSVNodzA3T2xmbEs="
  AWS_SECRET_ACCESS_KEY: "VENLSDhpRUY3WTNLRk05RnVwVnNhQ2tCWDlNeXpCZ1BrdzJreGUyaw=="
  AWS_ENDPOINT_URL: "aHR0cDovL21pbmlvLnN0b3JhZ2Uuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMA=="
  AWS_REGION: "dXMtZWFzdC0x"
  AWS_VERIFY_SSL: "ZmFsc2U="
  S3_USE_STREAMING: "dHJ1ZQ=="
