apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: euclid-catalog-mcp
  labels:
    app: euclid-catalog-mcp
  annotations:
    cert-manager.io/cluster-issuer: "self-signed-ca-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - catalog.euclid.mcp.ay.dev
      secretName: euclid-catalog-tls
  rules:
    - host: catalog.euclid.mcp.ay.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: euclid-catalog-mcp
                port:
                  number: 8000
