apiVersion: v1
kind: Secret
metadata:
  name: euclid-catalog-mcp-secret
  labels:
    app: euclid-catalog-mcp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ChdosFaZhIShw07OlflK"
  AWS_SECRET_ACCESS_KEY: "TCKH8iEF7Y3KFM9FupVsaCkBX9MyzBgPkw2kxe2k"
  AWS_ENDPOINT_URL: "http://minio.storage.svc.cluster.local:9000"
  AWS_REGION: "us-east-1"
  AWS_VERIFY_SSL: "false"
  S3_USE_STREAMING: "true"
